### ISSUE TITLE
FreeNAS 11.2 troubles - cannot access share using Samba

### ISSUE THREAD

**Issue by gorantornqvist** [hasse69/rar2fs#101]
Hi Hasse,
I tried an upgrade of FreeNAS from 9 to 11.2 which was just released.

Now I have trouble accessing my rar2fs samba file shares.
When trying to access the share using Windows Explorer I get: "The request is not supported"
I run rar2fs like:
/mnt/vol1/opt/rar2fs --seek-length=1 -oallow_other /mnt/path/to/my/rars /mnt/vol1/rar2fs_mount-point

Also tried building a new rar2fs using latest version but same issue.

Any suggestions?

Thanks...

**Comment by hasse69** [comment]
Hello, not really sure what might have happened there between FreeNAS 9 and 11.2? But from the looks of it (and on your site http://goran.tornqvist.ws/rar2fs-on-freenas-9-2-embeded/) problem started already before 11.2? And you tried same version of rar2fs? If this is a permission issue is should not be that hard to workaround using the uid/gid mount options, but "The request is not supported" could indicate something else. Can you try to start rar2fs with the -d flag (will log to console) and see what file system operations are being called when trying to access the mount point?

**Comment by hasse69** [comment]
Btw, did you check this link https://forums.freenas.org/index.php?threads/freenas-11-2-beta1-freenas-11-2-beta2-now-samba-no-longer-works-access-denied.69137/
Seems later versions of FreeNAS changes minimum required samba version and now Windows got confused? What if you change NT1?

**Comment by gorantornqvist** [comment]
Ok, so I guess the upgrade process did something with the file system permission or ACLs since when I booted up my backup usb stick of my previous freenas-9 install, the same problem occurrs.

The strange thing is though that the the share is readable before I run the rar2fs command ...
I will check those links more closely....thanks...

**Comment by hasse69** [comment]
The rar2fs file system knows nothing about how you chose to share it. if the Samba share does not work it is either a permission issue or something with the file system operations.

**Comment by gorantornqvist** [comment]
There´s some freenas magic going on here I think.
If I run rar2fs as a init script, I can access the samba share on freenas-9, not if I run rar2fs after boot.
On freenas-11 however, I cant access the share no matter what I try.
The mount is readable locally/thru ssh though which is the most important thing.

"something with the file system operations".  Are there any rar2fs options around this I can play with?

**Comment by gorantornqvist** [comment]
I get these errors when access the mount using samba.
`
getattr /
   unique: 1073, success, outsize: 112
unique: 1074, opcode: GETXATTR (22), nodeid: 1, insize: 63, pid: 8797
   unique: 1074, error: -78 (Function not implemented), outsize: 16
unique: 1075, opcode: GETATTR (3), nodeid: 1, insize: 40, pid: 8797
getattr /
   unique: 1075, success, outsize: 112
unique: 1076, opcode: GETATTR (3), nodeid: 1, insize: 40, pid: 8797
getattr /
   unique: 1076, success, outsize: 112
unique: 1077, opcode: GETATTR (3), nodeid: 1, insize: 40, pid: 8797
getattr /
   unique: 1077, success, outsize: 112
unique: 1078, opcode: GETATTR (3), nodeid: 1, insize: 40, pid: 8797
getattr /
   unique: 1078, success, outsize: 112
unique: 1079, opcode: GETXATTR (22), nodeid: 1, insize: 63, pid: 8797
   unique: 1079, error: -78 (Function not implemented), outsize: 16
unique: 1080, opcode: GETATTR (3), nodeid: 1, insize: 40, pid: 8797
getattr /
   unique: 1080, success, outsize: 112
unique: 1081, opcode: GETATTR (3), nodeid: 1, insize: 40, pid: 9131
getattr /
   unique: 1081, success, outsize: 112
`
That error doesnt appear if I do a ls /path/to/mount

**Comment by hasse69** [comment]
Can you attach your `config.log` here ? It is in the root of the rar2fs build folder.

**Comment by hasse69** [comment]
Well the problem here is that your jail does not seem to support any of the xattr-functions. This means that rar2fs cannot tie any callbacks to those file system operations and thus you will get an error from FUSE. So something has changed in the later versions of FreeNAS that suddenly starts to forward those calls to the file system, Or your jail has changed.

**Comment by hasse69** [comment]
Any news here?

**Comment by gorantornqvist** [comment]
Hi Hasse,
I also tried compiling straight on the FreeNAS appliance (by doing a mount_unionfs with the necesary files gcc tools etc located in the jail) but no luck so maybe its a freebsd-11 problem or maybe something has changed in my build environment.

I will probably revisit this when I get more time...

**Comment by hasse69** [comment]
Well, that is a problem then. You can perhaps try your old setup for comparison? Are there any `xattr` calls being made there? If not then something changed in the FreeNAS Samba/CIFS setup, most likely something that can be configured differently.

**Comment by hasse69** [comment]
Any updates?

**Comment by hasse69** [comment]
Did you check out this one?
https://forums.freenas.org/index.php?threads/rar2fs-and-freenas-11.56906/

**Comment by gorantornqvist** [comment]
Hi, thanks for the info and sorry for late reply...
At the moment I have no real need to use samba with rar2fs anymore.

Should I close the issue or should it be left open?

**Comment by hasse69** [comment]
I think we should close this issue since as I do not see this as a rar2fs problem, unless there are any strong objections of course.

**Comment by gorantornqvist** [comment]
Hi,
I just upgraded to FreeNAS-11.2-U2 (from U1) and rar2fs and samba sharing magically started working again ...

**Comment by hasse69** [comment]
I guess that confirms our initial suspicion that this was all about some wrong system configuration or lack of such. Please feel free to close the issue.
