### ISSUE TITLE
cannot configure/compile

### ISSUE THREAD

**Issue by platinum55** [hasse69/rar2fs#107]
hello,

i tried to configure/compile but it fails:

autoconf
configure.ac:9: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:13: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:27: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:501: error: possibly undefined macro: AM_ICONV

./configure --prefix=/usr
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config

using latest xubuntu 18.10 here, how to compile? :)

**Comment by platinum55** [comment]
"autoreconf -i" fixed it :)

**Comment by hasse69** [comment]
Hmm, did you actually read Q1.3 in the wiki ;)
