### ISSUE TITLE
Some files refuse to play

### ISSUE THREAD

**Issue by milesbenson** [hasse69/rar2fs#108]
Hi there,

i sometimes cannot play files from a rar2fs mount, although the mkv is shown fine. I tried with Plex, Kodi, VLC. Info for one of those files is:

Details: RAR 4, volume

    Name: playme.mkv
    Type: File
    Size: 1461755456
Packed size: 49999873
Ratio: -->
mtime: 2019-03-07 09:05:13,229348700
Attributes: ..A....
Pack-CRC32: 8FB23041
Host OS: Windows
Compression: RAR 3.0(v20) -m0 -md=128K

Any idea? The files play fine when unrared.

Regards,
m.

**Comment by hasse69** [comment]
Sorry, but based only on the information you provided here it is impossible to determine anything really.
Is it the same file/files that always fail or is it random? Best would be if you could provide such an archive so that I could try it myself.

**Comment by hasse69** [comment]
Also can you provide the output from
```
uname -a
rar2fs --version
ldd $(which rar2fs)
```

**Comment by milesbenson** [comment]
Is there a way to send you a private message for a link with a sample archive?

# uname -a
Linux shiva 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# rar2fs --version
rar2fs v1.27.1 (DLL version 8)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

ldd $(which rar2fs)
	linux-vdso.so.1 (0x00007ffd131bc000)
	libfuse.so.2 => /lib/x86_64-linux-gnu/libfuse.so.2 (0x00007f2470216000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f246fe8d000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f246fc85000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f246fa6d000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f246f84e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f246f45d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f246f259000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f246eebb000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f24706b8000)

**Comment by hasse69** [comment]
Sure, just mail a pointer to hans.beckerus AT gmail,com

**Comment by milesbenson** [comment]
You got mail :)

**Comment by hasse69** [comment]
Thanks, will look into it.

**Comment by hasse69** [comment]
I tried the sample archive and I have no issues what so ever to playback the contents.
I did however use WMP but that should not really matter.
Can you please `cd` to your local mount point and destination folder and try this:
```
hexdump -C -n 64 playme.mkv
```
Can you read it? Should result in a output like this:
```
00000000  1a 45 df a3 a3 42 86 81  01 42 f7 81 01 42 f2 81  |.E...B...B...B..|
00000010  04 42 f3 81 08 42 82 88  6d 61 74 72 6f 73 6b 61  |.B...B..matroska|
00000020  42 87 81 04 42 85 81 02  18 53 80 67 01 00 00 00  |B...B....S.g....|
00000030  57 20 9e 0c 11 4d 9b 74  af 4d bb 8c 53 ab 84 15  |W ...M.t.M..S...|
00000040
```
If that works then it must be some permission issue you are experiencing? 
How are you exporting your mount point?

**Comment by milesbenson** [comment]
Yes, hexdump does look like that. Permissions are 777, tried ro as well. The whole season is affected from the sample i gave you and permissions are the same for every folder/file in that subfolder, not only the season.

My rar2fs looks like this:
rar2fs -o rw,allow_other /path/to/tv-shows/ /path/to/rar2fs-tvshows/

I tried with --seek-length=1 as well, but no change.

**Comment by hasse69** [comment]
Ok, I did a diff of the uncompressed file and the one in the rar2fs mount and there was no difference. So extraction works just fine, at least for me. 
The `--seek-length=1` mount option would only increase the performance, not the actual result.
This was a bit weird. Since it works fine to hexdump the file it must be something related to the access.
Can you mount using the `-f` flag (foreground) and check if you see any access to the mount point at all when trying to playback the file?

**Comment by hasse69** [comment]
Also, add default_permissions to your set of mount options
`-o rw,allow_other,default_permissions`

**Comment by milesbenson** [comment]
Neither Kodi nor Plex show any access to the mount point with -f. That's strange, as everything else except that season plays fine. Ok there are some movies that do not work either, but it is very rare.

**Comment by hasse69** [comment]
If you try WMP or VLC directly to your mount point, what happens then?

**Comment by milesbenson** [comment]
VLC is just crashing, cannot test WMP as i have no windows at all

**Comment by hasse69** [comment]
Crashing? Hmm, but did it try to access the file at least?

**Comment by milesbenson** [comment]
Now it is getting weird:

ro,allow_other,default_permissions gives me playback in Kodi, playback in Plex Media Player, NO playback in Plex Browser app and a crashing VLC.

As it is playing in Plex Media Player and in Kodi, i'm fine :)

**Comment by hasse69** [comment]
I just tried it from Plex and playback works perfectly fine. I think there is something fishy with your uid/gid related to these files because what `-odefault_permissions` does should basically make things worse since this option instructs the kernel to perform its own permission check instead of deferring all permission checking to the filesystem.

**Comment by milesbenson** [comment]
Did you try within Chrome/Firefox? Or Plex Media Player?

**Comment by hasse69** [comment]
Tried both from PlexWeb and the iOS app.

**Comment by milesbenson** [comment]
iOS is working fine here, Safari/Chrome on macOS does not. Will try on Windows tomorrow in the office and let you know, and i will doublecheck the permissions again.

**Comment by milesbenson** [comment]
Mounting with uid and gid for the same user that is running plexmediaserver helps! Thank you very much for pushing me into the right direction
