### ISSUE TITLE
rar2fs mount not accessible inside docker container

### ISSUE THREAD

**Issue by NineBall8** [hasse69/rar2fs#110]
Hi!

I'm on rar2fs v1.27.2 running on a Synology DS415+ installed from Entware.
It works great everywhere, except within containers on the NAS.
Is this expected behaviour? And is there a way to get the mounted files show to show up?

Thanks for this awesome software!

**Comment by hasse69** [comment]
There is some information missing here, such as what is the actual behavior you see? Do you get some error message or files simply refuse to show?
If I google rar2fs and docker I get multiple hits so I do not really think there should be a problem using rar2fs mounts inside containers but you need to make sure you get all your permissions straight.

Google gave  me some hits specifically for synology.
Have you looked into those? Here is one at least
https://www.reddit.com/r/docker/comments/9o6tyg/rar2fs_on_sonology_docker/

**Comment by NineBall8** [comment]
Sorry about that!
The unrar-folder is empty. No error messages.
rar2fs is run on the base system and the Docker container on the same system does not show any files/folders in the unrar-folder. On the base system, everything works well.

Yep, I have seen that thread, I didn't see anything related to running on base system and not seeing the files inside dockers.

I very much appreciate you help, and will be more than happy to donate if I get it running, thanks!

**Comment by NineBall8** [comment]
Maybe containers needs special permissions/flags ("--device /dev/fuse --privileged" or something?) to be able to "see" mounted devices? I'd rather not give containers that high privilege though.

It might be more of a docker question?

**Comment by hasse69** [comment]
Yes, I suspect this being a very docker specific question and not something that can be traced down to a bug/problem in rar2fs. But if it does I will of course try to resolve any issues found.
Try some docker forum. Having the rar2fs mount on the base system to me sounds like something the container should not be able to see, not by default at least.

**Comment by NineBall8** [comment]
Haha, it was an easy fix.
After restarting the containers they see the mount! :)
No extra flags needed.

**Comment by hasse69** [comment]
Good to hear, will close this issue now since it seems to be resolved.
