### ISSUE TITLE
1.28.0 release archive doesn't contain man/rar2fs.1

### ISSUE THREAD

**Issue by Ingramz** [hasse69/rar2fs#120]
When `make` reaches `man` directory, it is unable to (re)make `rar2fs.1.gz`.

```
Making all in man
make[1]: Entering directory '/work/src/rar2fs-1.28.0/man'
make[1]: *** No rule to make target 'rar2fs.1', needed by 'rar2fs.1.gz'.  Stop.
```

**Comment by zimme** [comment]
Overrode it using `make SUBDIRS=src` as I don't need the man pages in my docker container.

**Comment by hasse69** [comment]
Ok, I will try to update the release TAR-ball.
In the mean-while, just checkout latest from using git.

**Comment by hasse69** [comment]
TAR-ball should be updated now, try downloading it again.

**Comment by zimme** [comment]
It works! :tada:

**Comment by hasse69** [comment]
Yes, it works, but it is not ok, it should not require the .gz file to be part of the distrobution.
Need to check this a bit more.

**Comment by zimme** [comment]
It wasn't the .gz file that was needed, from what I understood it was the `man/rar2fs.1` file that was missing so the compression of that file failed as it wasn't there and it only tries to compress the file if the dist has `gzip` installed when building.

**Comment by hasse69** [comment]
ok, I will block this release, and redo it. Sorry for the inconvenience.

**Comment by hasse69** [comment]
Should be fixed now. Had to force a push (not nice, I know, but that is what I did this time).

**Comment by hasse69** [comment]
Ah oh, yes...
You need to download the TAR-ball again if you wish to get the same a tag v1.28.0.

**Comment by zimme** [comment]
Rebuilt the rar2fs container locally using no cache so it downloaded everything again and it works! :tada: Will trigger a rebuild on docker hub 👍

**Comment by hasse69** [comment]
Ok, this is still broken because now as it does not install the .gz file anymore.
Ok, I will not fix this now. Not sure actually how to fix it either without adding the .gz to the distrobuted files and I do not wish to install both :(
