### ISSUE TITLE
Missing "large files"

### ISSUE THREAD

**Issue by Coradol** [hasse69/rar2fs#129]
When I mount multi volume rar files, i see all smaller not into the rar packed files, also smeller not packed proof mkv's. But i do not see the big files inside the rar, they are not listed / shown. It does not matter if the rar files are locally stored or mounted via cifs. 

Ubuntu 19.10
rar2fs v1.28.0-gitc223aa4 (DLL version 8)   
FUSE library version: 2.9.9
fusermount version: 2.9.9
using FUSE kernel interface version 7.19
unrarsrc 5.8.5

root@serv:/My.BD-Directory# unrar l my-bd.1080p.rar

UNRAR 5.61 beta 1 freeware      Copyright (c) 1993-2018 Alexander Roshal

Archive: my-bd.1080p.rar
Details: RAR 4, volume

 Attributes      Size     Date    Time   Name
----------- ---------  ---------- -----  ----
    ..A.... 14388414023  2019-07-31 00:37  my-bd.1080p.mkv
----------- ---------  ---------- -----  ----
          14388414023  volume 1          1

rar2fs My.BD-Directory /opt/ -o allow_root
root@serv:/# ls /opt/
notpacked_my-bd.1080p.jpg  notpacked_my-bd.1080.nfo (>>RAR CONTENT IS MISSING!)
root@serv:/#

**Comment by hasse69** [comment]
Can you please try to checkout v1.28.0 tag (latest stable release) since master/HEAD currently suffers from known issues.

**Comment by Coradol** [comment]
I cloned your mentioned branch version with: 

git clone --branch v1.28.0 https://github.com/hasse69/rar2fs.git

I recompiled it with the latest unrar sources and it works now.

Thanks!

**Comment by hasse69** [comment]
You can now try latest on master again since the suspected commit has been reverted.

**Comment by hasse69** [comment]
This was most likely a duplicate of issue #128 .
