### ISSUE TITLE
99% cpu use

### ISSUE THREAD

**Issue by jepz88** [hasse69/rar2fs#132]
Hi! LOVING this so much. Running it on a NUC with basically just rar2fs and Home Assistant. Mounted a few NAS to the NUC and doing the magic with rar2fs on there. Just a question - should the NUC (2019 i5, 16gb ram, ssd) running constantly on 99-100% cpu usage when watching a movie? Some 4k videos are buffering a lot. Should I live with this or is there a solution for this? Thanks Hasse!

**Comment by hasse69** [comment]
No, it does not sound right. 
Unfortunately I am not able to look into this until next week at best. But do you know if the archive is compressed or not? Please provide as much details as possible about the issue. For instance, does it affect all archives or just some etc.

**Comment by jepz88** [comment]
Thanks for answering!
Se version below. Running Plex on a Nvidia Shield TV, and the PMS on the Intel NUC. All wired to the network. Basically all movies gets the NUC to work really really hard, hearing it trying to cool down through my TV cabinet. 1080 movies rarely buffering, but 4K pretty often. Also getting a note on the TV (Plex) that the network is to slow. But this could not have to to with networking.. 

Running a mountscript, basically "mount -t cifs and then seek_length=0. Seems correct?

![image](https://user-images.githubusercontent.com/11645874/75178962-5d66ec00-5739-11ea-9ac2-3f928ce6b6b5.png)





rar2fs v1.28.0 (DLL version 8)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

**Comment by hasse69** [comment]
But is it PMS or rar2fs that is loading the system? Sounds to me that it is the PMS encoding that is the culprit here?

**Comment by jepz88** [comment]
Huh did not think about it that way.. It's loading my system only during playback. So what you are saying is that it could that perhaps be PMS trying to encode my videos and not play "pass through"? So then I dont have problem with the rar2fs?

**Comment by jepz88** [comment]
Just tried to playback a few different videos from iOS unit (iPhone 11 Pro Max) and told Plex to play original quality and no sub - then the CPU went down to about 10-15% instead. So feels like it is Plex who screws things up then?

**Comment by hasse69** [comment]
Using commands like ‘top’ etc will show what process(es) is in fact hogging the CPU. But yes, sounding on your description is seems to be related to PMS. In that case you need to post a question on the PLEX forums.

**Comment by hasse69** [comment]
Also note that my own experience with PMS and subtitles is that it is rather CPU heavy since PMS needs to recode the video to embed the subtitles.
Not saying that is the problem though.

**Comment by jepz88** [comment]
I have been experimenting a lot, and you are so right. When I play my 4K videos, even though i try not to transcode them, by playing with subtitles they transcode anyway. And the **Plex Transcoder** basically runs to max on all cores on my CPU. By playing without subtitles the **Plex Transcoder** process wont run at all and therefore my CPU will not go through the roof. So I guess I will have to take this problem with me and find a way to not make my videos transcode :) 

Big thanks to you Hasse! :)
