### ISSUE TITLE
question regarding exclude

### ISSUE THREAD

**Issue by Nischi85** [hasse69/rar2fs#143]
Questions below are for outside of rar-archives.

Is there some way to exclude with wildcard folders ? ex --exclude=/*/Sample/
Is there some way to exclude with wildcard for files? ex. --exclude=sample*.*

I've tried various variations withouch success.

**Comment by hasse69** [comment]
I believe something similar has been asked about before in issue #134
If you read the man page for rar2fs (https://github.com/hasse69/rar2fs/wiki/Manual-Page) I think you will find that the `--exclude` option (perhaps not the best name) has nothing to do really with filtering actual contents on your existing source folder or mount point. It is more about ignoring things that is *not* present in your back end file system.
Currently there is not way to filter files or directories in the way that you explain here.
But as I have mentioned in the previous issue, what exactly is the use case for needing such a feature?
Whatever you point to that looks beneath the mount point should be able to handle that for you?

**Comment by Nischi85** [comment]
Thank you hasse69.  tried searching for an answer, but I guess my google-skills wheren't up to the task.

My use case if I have a lot of uneeded files for my Emby-collection, and just wanted to "filter" them out.

Looks like that rofs-filtered will do the trick, thank you again!

**Comment by hasse69** [comment]
If you stack rofs-filtered on top of a rar2fs mount it is only the rofs-filtered mount point that will become read-only.
If you mounted read/write using rar2fs its mount point will remain writable. Then how that will affect the rofs-filtered caches (if any) etc I cannot answer.

Closing.
