### ISSUE TITLE
Override filenames

### ISSUE THREAD

**Issue by karibertils** [hasse69/rar2fs#145]
Compatability issue with file names inside archives and various software which relies on the file name to recognize the content. Nice workaround for this would be having an option that would replace filenames by using the folder name that contains the archive + the original file extension as the new name. In my case there's always just single file inside so that would be perfect. But might be good to revert to original behaviour if there are multiple files inside.

**Comment by hasse69** [comment]
First of all, this topic seems to cover two completely different requests/issues.
If we look at the first one
> Sometimes rar archives contain some folder structure causing trouble. Usually you can drill down through the folders and get to the content but not always.

That to me sounds like a bug and should be handled as such.

> Similar issue is shortening of file names inside the archives causing software which relies on the file name to not recognize the content. 

Can you please elaborate or give an example, I am not really sure I follow you here.

In general, the purpose of rar2fs is to mount RAR archives/folders and replicate the effect of having extracted the archive in place. I am not very keen on implementing modifications of the resulting file system structure which does not only make the whole process a lot more complex but also somewhat defeats the purpose of rar2fs. I believe that this kind of functionality should be provided by some other FUSE file system that can be stacked on top of rar2fs. There is an `alias` function that can be used to shadow/camouflage specific files (but not directories) which is probably how far rar2fs will ever allow this.

**Comment by hasse69** [comment]
Can you please file the path resolution problem as a seperate issue?
You have just found a a rather severe issue with rar2fs and I also discovered a regression test failure.
Your example does not work with v1.29.0, but some archives that did stopped working sometime after that release.

**Comment by karibertils** [comment]
I opened seperate issues. About the issue with filenames i will elaborate here.

For example using [Sonarr](https://github.com/Sonarr/Sonarr). Let's say you have ```Example/Example.S01E01/101.rar``` and inside the archive is file ```101.avi``` or ```a/b/c/d/e/anything.avi``` for that matter.

Sonarr and other media software, will not recognize what ```101.avi``` or ```anything.avi``` is, and will mark Example S01E01 as missing. If I extract and rename ```101.avi``` or ```anything.avi``` to ```Example.S01E01.avi``` Sonarr marks S01E01 found.

I don't know what's the most practical solution to this issue. Maybe another fuse file system could be used to handle this.

**Comment by hasse69** [comment]
I suggest you try out the `alias` feature, see `rarconfig.example`. if all you wish to do is to rename a file to something else that is what the `alias` feature can aid you with.

**Comment by karibertils** [comment]
OK I had not seen that feature yet. It works perfectly but I would have to put new entries in there continuously.

Would it be possible to support more dynamic syntax in rarconfig, something like this ?
```
[*.rar]
alias = "/*.mkv","/[archive_folder].mkv"

[*.rar]
alias = "/*.mp4","/[archive_folder].mp4"

[*.rar]
alias = "/*.avi","/[archive_folder].avi"
```

**Comment by hasse69** [comment]
Something like that could perhaps be done but there are currently no plans to extend this feature further.

**Comment by karibertils** [comment]
OK, good to know about the SIGHUP. I'll play around with this and should do the trick
