### ISSUE TITLE
How to install - Fedora 33

### ISSUE THREAD

**Issue by mac010** [hasse69/rar2fs#149]
Hi, sorry totally new to installing from source.
I am using Fedora 33 workstation edition.

Can i install this from a user account, without root? If so will selinux effect it?

Has anyone who runs Fedora tried this?

**Comment by hasse69** [comment]
> Can i install this from a user account, without root?

Yes you can, but not using 'make install' of course, you need to install it manually to somewhere your user has permission to write. Then if it works or not depends on your FUSE installation if it is done properly or not to allow access to /dev/fuse.

>   If so will selinux effect it?
I cannot answer that I am afraid. I suggest you try it and take if from there.

**Comment by hasse69** [comment]
I can also see now that Fedora ships with a lot of FUSE based packages already. I see no reason why rar2fs should not work in Fedora. 

https://fedoraproject.org/wiki/User:Peter/FUSE

**Comment by mac010** [comment]
> I can also see now that Fedora ships with a lot of FUSE based packages already. I see no reason why rar2fs should not work in Fedora.
> 
> https://fedoraproject.org/wiki/User:Peter/FUSE

Got it built and installed and works great! thanks a load for writing and maintaining this!

This should be in every distros repo

**Comment by hasse69** [comment]
Good that it worked out for you!
