### ISSUE TITLE
Look up files that are not actively used

### ISSUE THREAD

**Issue by havanalola** [hasse69/rar2fs#158]
Can I deactivate this, it unnecessarily goes through all the folders and caches the content that I do not need

it is enough for me if it only becomes active when I also actively call this path?

**Comment by hasse69** [comment]
Can you please elaborate? Because rar2fs does not look up something that it has not actively been requested to.

**Comment by havanalola** [comment]
I have no application where accesses these paths

My Mount is:

rar2fs -d -o allow_other -o warmup=0 --seek-length=1 /jail/glftpd/site/ /rar2fsmount/

`LOOKUP /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/02 - Foundational Concepts/09 - Setting up an Azure Subscription.mp4
getattr /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/02 - Foundational Concepts/09 - Setting up an Azure Subscription.mp4
   NODEID: 40349
   unique: 620782, success, outsize: 144
unique: 620783, opcode: LOOKUP (1), nodeid: 40341, insize: 87, pid: 4961
LOOKUP /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/02 - Foundational Concepts/10 - Getting Started with the Azure Portal.mp4
getattr /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/02 - Foundational Concepts/10 - Getting Started with the Azure Portal.mp4
   NODEID: 40350
   unique: 620783, success, outsize: 144
unique: 620784, opcode: LOOKUP (1), nodeid: 40341, insize: 85, pid: 4961
LOOKUP /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/02 - Foundational Concepts/11 - Creating Your First Virtual Machine.mp4
getattr /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/02 - Foundational Concepts/11 - Creating Your First Virtual Machine.mp4
   NODEID: 40351
   unique: 620784, success, outsize: 144
unique: 620785, opcode: LOOKUP (1), nodeid: 40341, insize: 79, pid: 4961
LOOKUP /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/02 - Foundational Concepts/12 - Configuring a Virtual Machine.mp4
getattr /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/02 - Foundational Concepts/12 - Configuring a Virtual Machine.mp4
   NODEID: 40352
   unique: 620785, success, outsize: 144
unique: 620786, opcode: RELEASEDIR (29), nodeid: 40341, insize: 64, pid: 0
releasedir[139836954788080] flags: 0x0
unique: 620787, opcode: LOOKUP (1), nodeid: 40338, insize: 109, pid: 4961
   unique: 620786, success, outsize: 16
LOOKUP /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/rebar-developing.with.dot.net.on.microsoft.azure.getting.started.nfo
getattr /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/rebar-developing.with.dot.net.on.microsoft.azure.getting.started.nfo
   NODEID: 40353
   unique: 620787, success, outsize: 144
unique: 620788, opcode: LOOKUP (1), nodeid: 40338, insize: 109, pid: 4961
LOOKUP /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/rebar-developing.with.dot.net.on.microsoft.azure.getting.started.sfv
getattr /APPS-PC/P/Pluralsight.Developing.With.Dot.NET.On.Microsoft.Azure.Getting.Started-REBAR/rebar-developing.with.dot.net.on.microsoft.azure.getting.started.sfv
   NODEID: 40354
   unique: 620788, success, outsize: 144
unique: 620789, opcode: RELEASEDIR (29), nodeid: 40338, insize: 64, pid: 0
releasedir[139837295532368] flags: 0x0
unique: 620790, opcode: LOOKUP (1), nodeid: 4105, insize: 113, pid: 4961
   unique: 620789, success, outsize: 16
LOOKUP /APPS-PC/P/Pluralsight.Developing.With.NET.On.Microsoft.Azure.Getting.Started-REBAR
getattr /APPS-PC/P/Pluralsight.Developing.With.NET.On.Microsoft.Azure.Getting.Started-REBAR
   NODEID: 40355
   unique: 620790, success, outsize: 144
unique: 620791, opcode: OPENDIR (27), nodeid: 40355, insize: 48, pid: 4961
opendir flags: 0x38800 /APPS-PC/P/Pluralsight.Developing.With.NET.On.Microsoft.Azure.Getting.Started-REBAR
   opendir[139837022257328] flags: 0x38800 /APPS-PC/P/Pluralsight.Developing.With.NET.On.Microsoft.Azure.Getting.Started-REBAR
   unique: 620791, success, outsize: 32
unique: 620792, opcode: READDIR (28), nodeid: 40355, insize: 80, pid: 4961
readdir[139837022257328] from 0
`

**Comment by havanalola** [comment]
I think the error is due to my locate cron which runs every 24 hours

**Comment by hasse69** [comment]
Why do you use the warmup option if you are not interested in populating the cache?

**Comment by havanalola** [comment]
I understood that with option -o warmup=0 this would be deactivated
i have changed the locate cron and my mount to
rar2fs -o allow_other --seek-length=1 /jail/glftpd/site/ /rar2fsmount/

**Comment by hasse69** [comment]
Sure, setting warmup to 0 means warmup is not triggered but then why give that option in the first place? No option no warmup, it is turned off by default.

**Comment by hasse69** [comment]
So I guess we can close this then now that you have found the reason?

**Comment by havanalola** [comment]
Yes. you can close
thx
