### ISSUE TITLE
warmup flag missing in --help command

### ISSUE THREAD

**Issue by jcastilloalonso** [hasse69/rar2fs#166]
I checked and rclone --help is missing -o warmup flag description and usage details. Might be good idea to include it in documentation for more people to be aware of it if needed.

**Comment by hasse69** [comment]
Please check latest version again. The help text should be there as well as described in the man-page.

**Comment by jcastilloalonso** [comment]
You are totally correct.  So sorry had in one machine running an older version (rar2fs v1.29.4) and it was not showing up, v1.29.5 shows the option at the end as expected. Thanks!
