### ISSUE TITLE
Add example for --seek-length flag in systemd unit

### ISSUE THREAD

**Issue by alethenorio** [hasse69/rar2fs#168]
I am using a systemd unit in rar2fs and I have looked everywhere but cannot find an answer on how do I configure rar2fs `--seek-length` flag in a systemd unit file.

Can we maybe add it as an example in Wiki?

**Comment by hasse69** [comment]
Sorry, I have very little experience with systemd mount units. But from what I can tell you should use the `Options=` section.
Is that not working?

**Comment by alethenorio** [comment]
I am also not good at systemd unit files. I have googled everywhere but couldn't find a lot of good documentation on the subject. I'll keep digging and see if I can find out how and update the issue

**Comment by hasse69** [comment]
So the example above did give you any additional clues?

**Comment by alethenorio** [comment]
Apologies. You are absolutely correct. I tried it out with a comma separation as you originally suggested and it seems to work (at least the directory mounts but I am not quite sure how to verify). Thank you.

Maybe add it as an example in the Wiki?

**Comment by hasse69** [comment]
I guess easiest way to verify is to misspell the option on purpose and verify that mount fails 😉

Yes, we can add it to the wiki? Should I give you write access so that you can do it once you have some real example to share?

**Comment by zappepappe** [comment]
Not sure for mounting with systemd, but for me htop will show the currently running rar2fs with mount points and options.

**Comment by alethenorio** [comment]
I'll be more than happy to write an example in the wiki.

@zappepappe Yeah I just checked PS and grepped by the process name and could verify as well

**Comment by hasse69** [comment]
@alethenorio you have been invited as a collaborator

**Comment by hasse69** [comment]
@alethenorio I saw that there was already some info about automount/mount and systemd in the wiki, maybe you can simply complement that with some info about adding additional arguments to the mount command.

**Comment by alethenorio** [comment]
Indeed. That was my plan. :)

**Comment by hasse69** [comment]
Please close the issue when you feel ready with your updates to the wiki.

**Comment by alethenorio** [comment]
Sorry for the delay here. It is now fixed.
