### ISSUE TITLE
rar2fs freezing occasionally

### ISSUE THREAD

**Issue by karibertils** [hasse69/rar2fs#172]
Running ```rar2fs v1.29.5-gitc87cd02``` with unrar ```6.0.7```.

From time to time the mountpoint will freeze. ```ls``` ```df``` etc will hang indefinently or until the rar2fs process is killed manually.

Running rar2fs through gdb these were the last lines before a freeze. The process was attached and logging when it froze. Gdb stopped logging and returned the prompt when it happened.

```
rar2_release()   
(1206219) RELEASE [0x7fffc001ad40    ]
Closing file handle 0x7fffac02b7d0
(1206219) FREE [0x7fffc001ad40    ]
rar2_releasedir()   
rar2_write()   
[New Thread 0x7fff90ff9700 (LWP 2632934)]
Thread 4378 "rar2fs" received signal SIG32, Real-time event 32.
[Switching to Thread 0x7fff9bbfd700 (LWP 2632914)]
futex_abstimed_wait_cancelable (private=0, abstime=0x7fff9bbfced0, clockid=-1681928624, expected=0, futex_word=0x7fffe000dec4) at ../sysdeps/nptl/futex-internal.h:323
323     ../sysdeps/nptl/futex-internal.h: No such file or directory.
(gdb) 
```

Accidentally closed gdb before taking backtrace, will do it next time.

**Comment by hasse69** [comment]
You need to mask SIG32 in gdb.

https://gnobal.net/591/what-is-sig32-during-a-gdb-debug-session

**Comment by karibertils** [comment]
Ahh I see. It happened again and I masked the SIG32 and continued. Process is running fine afterwards.

But these freeze are not the same as the ones I had previously. Since I was not using gdb. I will wait and see if the actual freezing issue shows up.

**Comment by gunnarrt** [comment]
This is something i wrote in previous thread, had an rpi4 running rar2fs 1.29.5, cant remember unrar version. but everytime i ran jellyfin instead of plex media server. sometimes as i had played a movie the rarmount used 100% cpu and i had to kill it manualy. Went to plex again and the issue disappered. Can fire it up later and se the unrar version and configure log.

**Comment by hasse69** [comment]
> sometimes as i had played a movie

The tense used is not irrelevant. If it gets stuck after content was extracted or while it was is very relevant since this is then more than likely the same issue as reported in #165.

**Comment by hasse69** [comment]
Any updates here?

**Comment by karibertils** [comment]
> Any updates here?

Nope, the issue has not shown itself again with heavy rar2fs use. It might as well have been hardware issue or something unrelated to rar2fs causing it last time.

Let's just close the issue. I will reopen if I manage to reproduce it again.
