### ISSUE TITLE
Docker releases

### ISSUE THREAD

**Issue by zimme** [hasse69/rar2fs#180]
Hey,

So I have a docker setup for rar2fs that's somewhat popular 100k+ pulls on docker hub (https://hub.docker.com/repository/docker/zimme/rar2fs).

I have no problem maintaining this, but I just wanted to check if there would be an interest to merge it with this repo?

Whenever you do a release of rar2fs, I manually just bump the rar2fs and rar version and publish a new version of the docker images, the "win" I could see with merging this is that the docker images would be "official" and automatically built and published whenever you release a new version of rar2fs.

If you would like to keep the docker stuff separate we could keep the docker stuff in my repo and perhaps we could setup a repository dispatch github action whenever publish releases so it would trigger a docker publish on my repo.

**Comment by hasse69** [comment]
If it is ok with you I rather not merge the two projects. The dependency you are facing here is not very uncommon and it is better each maintainer deals with the uplift if/when necessary.

**Comment by zimme** [comment]
No problem at all, as I said I'm completely fine with maintaining it and this was just a query to see if there were any interest.
