### ISSUE TITLE
Cannot build `rar2fs` with `unrar` 7.0.7

### ISSUE THREAD

**Issue by fdegros** [hasse69/rar2fs#186]
It looks like the field [`FileHeader::RedirName`](https://github.com/pmachapman/unrar/blob/05567f51502f156685e346fa072755ea07738edf/headers.hpp#L252) has changed its type from `wchar_t*` to `std::wstring`, which prevents the compilation of `rar2fs` with `unrar` 7.0.7:

See https://bugs.gentoo.org/931078

```
dllext.cpp: In function ‘int RARListArchiveEx(void*, RARArchiveDataEx**)’:
dllext.cpp:174:46: error: cannot convert ‘std::wstring’ {aka ‘std::__cxx11::basic_string<wchar_t>’} to ‘const wchar_t*’
  174 |           wcscpy(N->LinkTargetW,Arc.FileHead.RedirName);
      |                                 ~~~~~~~~~~~~~^~~~~~~~~
      |                                              |
      |                                              std::wstring {aka std::__cxx11::basic_string<wchar_t>}
```

The constant `NM` seems to have been removed as well:

See https://bugs.gentoo.org/930341

```
dllext.cpp: In function void RARNextVolumeName(char*, bool):
dllext.cpp:214:18: error: NM was not declared in this scope
  214 |   wchar NextName[NM];
      |                  ^~
```

**Comment by correabuscar** [comment]
so, is anyone working on a patch for this? trying to avoid the possibility of duplicating work here

**Comment by hasse69** [comment]
Looking at the UnRAR source code usually provides enough details to complete the small extension(s) in rar2fs. The extensions are simply variants of already existing functions.
