### ISSUE TITLE
Publishing a 1.29.7 release

### ISSUE THREAD

**Issue by heitbaum** [hasse69/rar2fs#192]
hi @hasse69  are you going to publish a release tar.gz? Thanks in advance.

https://github.com/hasse69/rar2fs/releases/download/v1.29.7/rar2fs-1.29.7.tar.gz

**Comment by hasse69** [comment]
There is a release made and I assumed the artifacts produced by the release flow was enough. So no, I had no plans of delivering additional artifacts.

**Comment by heitbaum** [comment]
> There is a release made and I assumed the artifacts produced by the release flow was enough. So no, I had no plans of delivering additional artifacts.

Thanks. I’ll target the “automatically built source.tar.gz” instead of the “numbered file” as was previous with 1.29.6.

**Comment by hartmark** [comment]
Can we please have a stable link to the source tar?

I want to be able for certain have the correct tarball for building packages.

I'm maintaining the AUR package:
https://aur.archlinux.org/packages/rar2fs

And the practice is that the source tarball is checksummed and compared after downloading to minimize supply attacks.

**Comment by hartmark** [comment]
AUR package is now using the new tarball and I have bumped it up to use unrar 7.0.9 aswell. It seems to be working without any issues.

**Comment by hasse69** [comment]
Not sure I understand? Are the artifacts provided by GitHub release flow enough or do we need to add something on top of it?

**Comment by hartmark** [comment]
I was a bit unclear.

The old tarball had the configure script already so I could just it without messing with autoconf. Now I have to run autoconf so I get the configure and makefiles.

See the build() function in this build file for how I build it.

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rar2fs

**Comment by heitbaum** [comment]
> I was a bit unclear.
> 
> The old tarball had the configure script already so I could just it without messing with autoconf. Now I have to run autoconf so I get the configure and makefiles.
> 
> See the build() function in this build file for how I build it.
> 
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rar2fs

I changed the LibreELEC build to use autotools too (which I somewhat prefer - thus the patch to autoconf)

**Comment by hasse69** [comment]
I can see if we can add also the 'make dist' generated tar-ball. This was simply a test to see if the artifacts provided by GitHub was sufficient or not.

**Comment by hartmark** [comment]
For me the artifacts were sufficient for building the package on Arch Linux.

I also made an AUR package that will track the master branch
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rar2fs-git
