### ISSUE TITLE
Dokan issue

### ISSUE THREAD

**Issue by AireagoirSteam** [hasse69/rar2fs#194]
I believe the build for dokany is out of date since its looking for dokan 1 and the current builds are dokan2.
running on the current version of cygwin and dokany 2.2.0

checking for fuse.h... yes
checking for fuse_new in -losxfuse_i64... no
checking for fuse_new in -losxfuse... no
checking for fuse_new in -lfuse_ino64... no
checking for fuse_new in -lfuse4x... no
checking for fuse_new in -lfuse... no
checking for fuse_new in -ldokanfuse1.dll... no

![Screenshot 2024-09-04 005107](https://github.com/user-attachments/assets/5b3abab4-e7c2-4686-913b-3362507ff840)

**Comment by hasse69** [comment]
Thanks for the observation. Try to simply add dokan2 to the search in configure.ac. If that works feel free to upload a pull request.

**Comment by AireagoirSteam** [comment]
So would I change the libdokan1 to libdokan2 or add a new line?

**Comment by hasse69** [comment]
The second option would be preferred for backwards compatibility. But please be aware that the dokan2 library has never been tested, at least not be me, so you're walking into unknown territory here.

**Comment by AireagoirSteam** [comment]
got it working by at least changing configure ac to dokan2 

if add dokan2 would be better as you said for backwards compatability since i tried by copying dokan1.dll line underneath and updating it to dokan2 and it didnt compile maybe put it in wrong place?

also followed these steps
unzip dokan.zip
chmod -R 777 x64
cp x64/Cygwin/cygdokanfuse2.dll /usr/bin
cp -R x64/Cygwin/lib/* /usr/lib
cp -R x64/Cygwin/include/* /usr/include

then make and it compiled.

**Comment by hasse69** [comment]
Not really sure what you mean. My point was to only add one extra lookup in the list like this
```
                    [ AC_CHECK_LIB(dokanfuse2.dll,fuse_new, [FUSE_LIBS="-ldokanfuse2.dll"],
                           [ AC_CHECK_LIB(dokanfuse1.dll,fuse_new, [FUSE_LIBS="-ldokanfuse1.dll"],
                                 [AC_MSG_ERROR([
                                         Cannot find fuse library - add alternative library search path using
                                         --with-fuse-lib and rerun configure. ])
                    ],)
```
This would first check for the presence of dokanfuse2 and if that does not exist, look for dokanfuse1. In that way, for a system that has both (for some unknown reason), it would pickup the latest first. Is there something I have overlooked with this approach?

**Comment by AireagoirSteam** [comment]
I mean I tried the other way ound looking for dokan1 then dokan 2 but I wrote the dokan2 part wrong so it failed

I'll add the changes on my end and test of it works

**Comment by hasse69** [comment]
Checking for dokan1 before dokan2 is a bit flawed and effectively breaks any wish to prioritize newer versions before old.

**Comment by AireagoirSteam** [comment]
tried your changes in configure ac

heres the output

/usr/bin/m4:configure.ac:308: ERROR: end of file in string
autom4te-2.72: error: /usr/bin/m4 failed with exit status: 1
aclocal-1.17: error: /usr/bin/autom4te-2.72 failed with exit status: 1
autoreconf-2.72: error: aclocal failed with exit status: 1

heres the changed file incase I did something wrong
[configure.ac.txt](https://github.com/user-attachments/files/16919817/configure.ac.txt)

**Comment by hasse69** [comment]
You added one more condition, you need to terminate it properly as well by adding yet another 

],)

**Comment by AireagoirSteam** [comment]
Think I've got it now
![Screenshot 2024-09-11 180039](https://github.com/user-attachments/assets/b3a7678a-950c-4bef-a50d-a9d2783d03e5)

**Comment by AireagoirSteam** [comment]
seems to hve built now

**Comment by hasse69** [comment]
Make a pull request and then we can merge it to master branch.

**Comment by AireagoirSteam** [comment]
Added pull request.
