### ISSUE TITLE
Permission issues in Jellyfin media server

### ISSUE THREAD

**Issue by aliak74** [hasse69/rar2fs#199]
Not sure if this is the problem of rar2fs and cygwin fuse.
This was working and suddenly i get messages in jellyfin server that i have permission issues only on video files. And these files are all Rar2fs network drives. This is how the permission are showing in windows security right now, is it like it should be? (only special rights)

![image](https://github.com/user-attachments/assets/464b0bb2-dba0-479f-86d3-775d6f746161)

**Comment by hasse69** [comment]
Really cannot say, I assume you are using WinFsp? In that case I would recommend throwing a question towards that project.

**Comment by aliak74** [comment]
I found out the issue was something with permissions inside jellyfin server.
