### ISSUE TITLE
Add support for Windows via Callback Filesystem?

### ISSUE THREAD

**Issue by ljani** [hasse69/rar2fs#39]
[Callback File System](https://www.eldos.com/cbfs/) claims to [support easy porting of FUSE modules to Windows](https://www.eldos.com/cbfs/fuse-to-cbfs.php) with MinGW.

An evaluation version of Callback File System is available for [download](https://www.eldos.com/cbfs/download-release.php#product) on their home page. The package contains the required libraries as well as samples. To actually run the binary, you'll need a free evaluation key, [available on their site](https://www.eldos.com/cbfs/keyreq/) as well.

What do you think? Too much work?

**Comment by hasse69** [comment]
I can not even compile the simplest sample that is provided by this package :(

```
$ make
mingw32-g++ -g -c -I../../../../CPP -I../../../CPP/MinGW -I../../../CPP/FUSE -I.
./../../../FUSE_CPP -I.. -D_REENTRANT -D_THREAD_SAFE -D_UNICODE -DUNICODE -D_WIN
32_IE=0x0300 -D_FILE_OFFSET_BITS=64 -Wno-write-strings -Wno-conversion-null -fpermissive ../fusexmp.c
In file included from c:\mingw\include\unistd.h:95:0,
                 from ../fusexmp.c:28:
c:\mingw\include\parts\time.h:65:8: error: redefinition of 'struct timespec' struct timespec
        ^
In file included from ../../../CPP/FUSE/fuse.h:34:0,
                 from ../fusexmp.c:22:
../../../CPP/FUSE/fusecbfs.h:68:8: error: previous definition of 'struct timespec'
 struct timespec {
        ^
make: *** [../fusexmp.o] Error 1
```

I would not hold my breath on this one! The CBFS is a strict commercial product and, from what I can tell, has no intentions what so ever of supporting the Open Source community. Just the fact that the company behind this refuses me to even use a gmail account to request for the evaluation license makes me slightly uncomfortable to say the least.
For that reason alone I feel it is simply a waste of time and energy trying to get this to work. Sorry, but feel free to experiment with it yourself. If you manage to get past the simple step of compiling their so called "sample" program using Mingw let me know. I might reconsider, even if I doubt it.

**Comment by ljani** [comment]
Thanks for taking interest! I kinda expected this, but there's no harm in asking.

I got the driver to compile by:
- Passing `-D__MSVCRT_VERSION__=0x0601` to `g++` (patch the makefile)
- Patching `fusecbfs.h` to use `#define stat __stat64` instead of `_stat64`
Google told me some discussion related to these changes in MinGW in general..

And the sample:
- Pass `-D__MSVCRT_VERSION__=0x0601 -D_TIMESPEC_DEFINED` to `g++` (patch the makefile)
- Add `#undef stat` at the end of `fusecbfs.h` (before `#endif //_CBFS_FUSE_USER_LIB_`)

I tried to compile `rar2fs` under MinGW but didn't get very far.. Here's my progress so far:
- Compile the driver in `CPP\FUSE` (see notes above)
- Add `#ifndef uid_t` and `#ifndef gid_t` around the `typedefs` in `fusecbfs.h`, otherwise you'll get duplicate definitions
- `configure.ac` should read something like this:
```
case "$host" in
     *-*-mingw*)
            FUSE_LIBS="-lfusecbfs"
        ;;
     *)
AC_CHECK_LIB(fuse4x,fuse_new, [FUSE_LIBS="-lfuse4x"],
    [ AC_CHECK_LIB(fuse_ino64,fuse_new, [FUSE_LIBS="-lfuse_ino64"],
        [ AC_CHECK_LIB(fuse,fuse_new, [FUSE_LIBS="-lfuse"],
            [ AC_CHECK_LIB(osxfuse,fuse_new, [FUSE_LIBS="-losxfuse"],
                [AC_MSG_ERROR([
                    Can't find fuse library - add alternative library search path using
                    --with-fuse-lib and rerun configure. ])
            ],)
        ],)
    ],)
],)
        ;;
esac
```
- Then run `autoreconf -f -i && ./configure --with-fuse=/home/Jani/CPP/FUSE/ CPPFLAGS="-x c++ -D_TIMESPEC_DEFINED -I/home/Jani/CPP/MinGW" --with-fuse-lib=/home/Jani/CPP/FUSE/ LDFLAGS="-L/home/Jani/CPP/MinGW/ -lcbfs"`
- This fails to check the fuse version because `FUSE_MAJOR_VERSION` and `FUSE_MINOR_VERSION` are not defined

**Comment by hasse69** [comment]
Just remove the check for FUSE_MAJOR_VERSION in configure.ac or patch the CBFS/FUSE header files. It is not a problem with fuse_version(), it seems to be that this package does not define FUSE_MAJOR_VERSION and FUSE_MINOR_VERSION.

**Comment by hasse69** [comment]
I managed to build the UnRAR source library after some struggle.
One of the most anoying facts seems to be that the `swprintf()` family of functions on Windows takes less arguments than the Unix variant!? Specifically it is the size argument that is not present on Windows! If simply removing the use of that argument is going to work will remain a mystery for a while.

The gcc in MinGW seems to enable a few more warnings by default than what seems to be standard. For that reason remove the Makefile needs to be slightly modified:
- Remove use of -fPIC, -DRAR_SMP and -lpthread
- Add creation of a static library using `ar rcs libunrar.a *.o` (this can be done manually after build)

The source code (.cpp files) need several changes, preferably using `__MINGW32__` conditional:
- all `swprintf()` functions must remove the size argument.
- the `strnlen()` function does not seem to exist and need to be replaced by standard strlen() followed by a check for size > n.
- In win32lnk.cpp remove the typedef of  `struct  _REPARSE_DATA_BUFFER` and pointer declaration of `PREPARSE_DATA_BUFFER` since it is already defined by MinGW. 

It does not build completely clean, but almost.
Now add `--with-unrar` and `--with-unrar-lib` when running ./configure.

Having problems though with `RARGetDllVersion()`, it seems it cannot resolve it.
But the function is there, but looks scrambled when it should not be.
```
$ nm -a unrar/libunrar.a | grep RARGetDll
000000c0 T _RARGetDllVersion@0
```

I might have missed something, but this is it for today!

**Comment by hasse69** [comment]
It is the use of the `PASCAL` data type that confuses autoconf. `AC_CHECK_LIB` is not made for finding C++ functions like this on Windows since PASCAL mangles the function prototype.
I will need to use `AC_TRY_LINK` instead, but until then simply bypass the check.

**Comment by vadmium** [comment]
Hello, this could be a waste of time, but have you looked at using Dokan at all? <https://web.archive.org/web/20150511010630/http://dokan-dev.net/en/>, <https://github.com/Maxhy/dokany>? It is an open source project and apparently has a FUSE API, but I haven’t investigated it closely.

**Comment by ljani** [comment]
@hasse69 thanks for the pointers. Yeah, I had to run after reaching the version check. I'll try to catch up with your work now :)

You can get `swprintf` to work by `#define swprintf _snwprintf`. It's a little less labour that way.

Windows uses `__stdcall` instead of `__cdecl` indeed.. I solved that issue with the libfusecbfs too by bypassing the check altogether.

**Comment by ljani** [comment]
@vadmium Do you have any pointers to the FUSE API?

This seems to do the `swprintf` problem better (`os.hpp`, right after `WIN32_LEAN_AND_MEAN`):
```
#define swprintf _snwprintf
#define vswprintf _vsnwprintf
#define __STRICT_ANSI__
```

**Comment by ljani** [comment]
Patching away those rar checks, I get this:
```
checking for source revision in SVN... no
checking for commit hash in git repo... e08a828
checking for sched_setaffinity... no
checking scandir ARG3 => const struct dirent * ... not ok
checking scandir ARG3 => struct dirent * ... not ok
configure: error: scandir unable to find a working combination
```

The log says:
```
conftest.c:81:34: error: 'alphasort' was not declared in this scope
   scandir(dir, namelist, select, alphasort);
                                  ^
conftest.c:81:43: error: 'scandir' was not declared in this scope
   scandir(dir, namelist, select, alphasort);
```

Now I'm lost..

**Comment by hasse69** [comment]
From the scandir(3) man page:
```
alphasort() and scandir() are specified in POSIX.1-2008, and are widely available. versionsort() is a GNU extension.
```

So either MinGW does not provide it, or it is called something else.

**Comment by ljani** [comment]
Hmm, I just moved to [`msys2`](http://sourceforge.net/projects/msys2/)/`mingw-w64-i686` and `libfusecbfs.a` seems to compile without modifications. Also `libunrar` can be installed via `pacman`.

Here's my progress with `msys2`:
- Install `msys2` from [here](http://sourceforge.net/projects/msys2/files/Base/x86_64/). I used `msys2-base-x86_64-20150512.tar.xz`
- Run `mingw32_shell.bat` and restart it after it has done the initial setup
- If your `msys2` is old do this:
```
pacman -Sy
pacman --needed -S bash pacman pacman-mirrors msys2-runtime
RESTART THE SHELL HERE
pacman -Su
```
- Unzip the CBFS driver
- Continue here:
```
pacman -S base-devel git mingw-w64-i686-gcc
cd ~/CPP/FUSE
make
git clone https://github.com/hasse69/rar2fs.git
export LANG=en_US.UTF-8
autoreconf -f -i
```

**Comment by hasse69** [comment]
You still need the complete source of UnRAR to build rar2fs. If you install libunrar through pacman make sure you download a matching version of the source.

**Comment by ljani** [comment]
Yeah, well, to thing about it, it won't work.. `libunrar` provided by `pacman` is 64-bit and we need 32-bit..

`unrar` also compiles fine without modifications, but there's lots of warnings: ` warning: -fPIC ignored for target (all code is position independent)`. I guess I should remove that flag again.

**Comment by hasse69** [comment]
I still get issues with _stat64 when compiling the driver :(

**Comment by ljani** [comment]
Are you using the already patched files? Make sure you revert any changes done to `stat`. Ie the line must read `#define stat _stat64`

**Comment by ljani** [comment]
And here we are..

```
checking scandir ARG3 => const struct dirent * ... not ok
checking scandir ARG3 => struct dirent * ... not ok
configure: error: scandir unable to find a working combination
```

```
checking scandir ARG3 => const struct dirent * ... not ok
checking scandir ARG3 => struct dirent * ... not ok
configure: error: scandir unable to find a working combination
```

**Comment by hasse69** [comment]
I use the 32-bit toolchain, that is probably why. I am on a 32-bit Windows 8 platform.
My build require the same changes as before.

**Comment by ljani** [comment]
Oh, yeah, I'm on 64-bit Windows 8.1.

Any idea how to use a third party `scandir` implementation with the configure? [Here's one](https://github.com/ggreer/the_silver_searcher/blob/77427e3de71978c883b5cbd0079d920d75698e8a/src/scandir.c)

**Comment by ljani** [comment]
Oh, it's in `msys2-runtime-devel`. But if I add `-I/usr/include/sys/` to `CPPFLAGS`, it fails with ```
checking whether we are cross compiling... configure: error: in `/home/Jani/rar2      fs':
configure: error: cannot run C compiled programs.
```
I guess that's because `msys2-runtime-devel` is 64-bit so it gets confused about something.

**Comment by hasse69** [comment]
Why compile using a 64-bit toolchain, use the pure 32-bit one instead should still work?

**Comment by hasse69** [comment]
You should add /usr/include to the include path, sys is implicit. But why is that not part of the default system search path!?

**Comment by hasse69** [comment]
I am sort of giving up on on this one! Now I cannot even compile the driver anymore. I complains about tchar.h not being found!

**Comment by ljani** [comment]
I guess the include path has something to do with the cross compiling and thus we can't include `/usr/include`. Btw, with `-I/usr/include` I get lots of warnings:
```
checking sys/statvfs.h presence... yes
configure: WARNING: sys/statvfs.h: present but cannot be compiled
configure: WARNING: sys/statvfs.h:     check for missing prerequisite headers?
configure: WARNING: sys/statvfs.h: see the Autoconf documentation
configure: WARNING: sys/statvfs.h:     section "Present But Cannot Be Compiled"
configure: WARNING: sys/statvfs.h: proceeding with the compiler's result
configure: WARNING:     ## ---------------------------------------------- ##
configure: WARNING:     ## Report this to http://code.google.com/p/rar2fs ##
configure: WARNING:     ## ---------------------------------------------- ##
checking for sys/statvfs.h... no
...
checking ucontext.h presence... yes
configure: WARNING: ucontext.h: present but cannot be compiled
configure: WARNING: ucontext.h:     check for missing prerequisite headers?
configure: WARNING: ucontext.h: see the Autoconf documentation
configure: WARNING: ucontext.h:     section "Present But Cannot Be Compiled"
configure: WARNING: ucontext.h: proceeding with the compiler's result
configure: WARNING:     ## ---------------------------------------------- ##
configure: WARNING:     ## Report this to http://code.google.com/p/rar2fs ##
configure: WARNING:     ## ---------------------------------------------- ##
checking for ucontext.h... no
...
checking fuse.h presence... yes
configure: WARNING: fuse.h: present but cannot be compiled
configure: WARNING: fuse.h:     check for missing prerequisite headers?
configure: WARNING: fuse.h: see the Autoconf documentation
configure: WARNING: fuse.h:     section "Present But Cannot Be Compiled"
configure: WARNING: fuse.h: proceeding with the compiler's result
configure: WARNING:     ## ---------------------------------------------- ##
configure: WARNING:     ## Report this to http://code.google.com/p/rar2fs ##
configure: WARNING:     ## ---------------------------------------------- ##
checking for fuse.h... no
configure: error:
        Can't find fuse.h - add alternative include search path using
        --with-fuse and rerun configure.
```
So I'm quite sure that's not the correct way to continue. I should understand how `scandir` affects configure and try to add a 3rd party implementation.

Heh, have you messed up your include path?

Yeah, I'm kinda in the same boat, plus I don't know autoconf. One thing I know is [the silver searcher](https://github.com/ggreer/the_silver_searcher/) can be compiled on Windows if it helps anyone.

**Comment by hasse69** [comment]
There seems to be some inconsitency here.
The i686-w64 compiler has all the needed header files and libraries for building the driver, but it does not have support for eg. `scandir()` and `select()`. Both which are needed to compile rar2fs.
The native msys2 compiler supports both, but then it is not a cross compiler and is missing support for eg. the Windows specific `tchar.h` header file. So the driver cannot be compiled using it.
A little bit of a chicken and egg problem :(

**Comment by ljani** [comment]
Yeah, I agree. I kinda gave up on this and decided to experiment with the driver and C#. Got it working pretty nice, but now I need to find a C# library that supports seeking non-compressed RARs.. Without seeking it's working already :)

**Comment by hasse69** [comment]
There is nothing wrong with a bit of competition :)
I am closing this issue now because even if it is possible (everything is) I think it will take a bit too much time to make it work using msys2 or similar. Maybe Dokan is another path to try as stated before? Feel free to contact me if you need any further assistance in your attempts of getting something to work on Windows.

**Comment by hasse69** [comment]
Actually I will leave it open. Maybe someone else is more successful in picking up were we left of?

**Comment by ljani** [comment]
Open issues do invite more discussion indeed.

I wonder how portable the current rar2fs code is, apart from autotools.. If I skipped the whole FUSE API and used matching CBFS/Dokan APIs directly from a different toolchain (VS).

**Comment by hasse69** [comment]
I would say rar2fs is very portable, assuming a POSIX compliant platform with FUSE support.
Windows was never really up on the table.

**Comment by jyhpsycho** [comment]
WIth msys2, it's possible to use many POSIX-compliant functionalities like pthread, not all though (at least FUSE will not work because it uses system call provided by Linux kernel, and Windows kernel does not provide functions like that).

It seems that "Callback File System" is one of VFS-like driver for Windows, and provides "Compatibility layer" for existing FUSE modules. I have very interesting of that and I'll try it if there's some free time to me... :-)

**Comment by hasse69** [comment]
There is an alternative method to do this which will be followed up in issue #75 .
Will close this one for now.
