### ISSUE TITLE
Compilation failed with GCC 6 series.

### ISSUE THREAD

**Issue by jyhpsycho** [hasse69/rar2fs#48]
On gentoo, rar2fs 1.22.0 failed to build throwing following error:
```
dllext.cpp: In function ‘size_t ListFileHeader(wchar*, Archive&)’:
dllext.cpp:539:33: error: unable to find string literal operator ‘operator""StringId’ with ‘const wchar_t [1]’, ‘long unsigned int’ arguments
 #define St(StringId) L""StringId""
                                 ^
dllext.cpp:650:38: note: in expansion of macro ‘St’
   wcs += msprintf(wcs, L"\n%12s: %s",St(MListName),Name);
```

I guess it's related on default C++ standard version. GCC 6 switched to C++14 by default, and I heard that string literal macro like that should have some space between tokens like following - I don't have an assertion, though.
```
#define St(StringId) L"" StringId ""
```

I'll test it and provide patch if it does.

**Comment by jyhpsycho** [comment]
OK, Verified. Please apply following patch for newer C++ standard support.

[rar2fs-1.22.0-gcc6-fix.patch.zip](https://github.com/hasse69/rar2fs/files/242854/rar2fs-1.22.0-gcc6-fix.patch.zip)

**Comment by hasse69** [comment]
Thanks, Patch applied to master.
