### ISSUE TITLE
Debian stretch easy install,  example usage with mplayer / gmplayer

### ISSUE THREAD

**Issue by luxigo** [hasse69/rar2fs#54]
https://gist.github.com/luxigo/9cc9c62037d33d822abb10d498d98e45

Not really a big issue, but could be usefull to others.

VLC is broken actuall for my video card using Debian stretch, so I needed a replacement to play rar archives with hasse without hassle...

Thanks !

**Comment by hasse69** [comment]
Thanks for the link.
I will see what to make of it, The issue report system is not the best of places since they will be hidden once closed. Maybe a post to the rar2fs group is better?

**Comment by hasse69** [comment]
Closing this since it is not really an issue report.
