### ISSUE TITLE
Diff between extracted rars and mounted rars, extra rar data in virtual file

### ISSUE THREAD

**Issue by tfiskgul** [hasse69/rar2fs#62]
Using rar2fs 1.23.1 compiled using Gentoo I get a different md5sum from the extracted contents of a multiple rar archive and the mounted one.

GCC version used is "gcc version 5.4.0 (Gentoo 5.4.0-r2 p1.2, pie-0.6.5) "

When using hexdump -C to compare the files, I see some extra output that is unwanted. This the beginning of the extracted original file:

00000000  52 49 46 46 00 21 9b 2b  41 56 49 20 4c 49 53 54  |RIFF.!.+AVI LIST|
00000010  b6 22 00 00 68 64 72 6c  61 76 69 68 38 00 00 00  |."..hdrlavih8...|
00000020  ec a2 00 00 00 00 00 00  00 00 00 00 10 01 00 00  |................|
00000030  e4 35 01 00 00 00 00 00  02 00 00 00 00 00 00 00  |.5..............|
00000040  40 02 00 00 b0 01 00 00  00 00 00 00 00 00 00 00  |@...............|
00000050  00 00 00 00 00 00 00 00  4c 49 53 54 d8 10 00 00  |........LIST....|
00000060  73 74 72 6c 73 74 72 68  38 00 00 00 76 69 64 73  |strlstrh8...vids|
00000070  78 76 69 64 00 00 00 00  00 00 00 00 00 00 00 00  |xvid............|
00000080  7d 00 00 00 b5 0b 00 00  00 00 00 00 e4 35 01 00  |}............5..|
00000090  64 3a 01 00 10 27 00 00  00 00 00 00 00 00 00 00  |d:...'..........|
000000a0  40 02 b0 01 73 74 72 66  6c 00 00 00 28 00 00 00  |@...strfl...(...|
000000b0  40 02 00 00 b0 01 00 00  01 00 10 00 58 56 49 44  |@...........XVID|
000000c0  00 c8 16 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000d0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

Looking at the rar2fs mounted file, there is some additional data before the RIFF section (I replaced a file name with from the rar in this output). 

00000000  52 61 72 21 1a 07 00 51  fc 73 41 00 0d 00 00 00  |Rar!...Q.sA.....|
00000010  00 00 00 00 1c b4 74 42  80 55 00 4f ed e3 00 00  |......tB.U.O....|
00000020  28 9b 2b 02 93 07 74 dc  3b ad 57 30 14 30 35 00  |(.+...t.;.W0.05.|
00000030  20 00 00 00 74 68 69 73  5f 77 61 73 5f 61 5f 66  | ...this_was_a_f|
00000040  69 6c 65 5f 6e 61 6d 65  5f 6f 66 5f 61 5f 66 69  |ile_name_of_a_fi|
00000050  6c 65 5f 69 6e 5f 74 68  65 5f 72 61 72 20 20 20  |le_in_the_rar   |
00000060  20 20 20 20 20 20 20 20  20 52 49 46 46 00 21 9b  |         RIFF.!.|
00000070  2b 41 56 49 20 4c 49 53  54 b6 22 00 00 68 64 72  |+AVI LIST."..hdr|
00000080  6c 61 76 69 68 38 00 00  00 ec a2 00 00 00 00 00  |lavih8..........|
00000090  00 00 00 00 00 10 01 00  00 e4 35 01 00 00 00 00  |..........5.....|
000000a0  00 02 00 00 00 00 00 00  00 40 02 00 00 b0 01 00  |.........@......|
000000b0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
000000c0  00 4c 49 53 54 d8 10 00  00 73 74 72 6c 73 74 72  |.LIST....strlstr|
000000d0  68 38 00 00 00 76 69 64  73 78 76 69 64 00 00 00  |h8...vidsxvid...|
000000e0  00 00 00 00 00 00 00 00  00 7d 00 00 00 b5 0b 00  |.........}......|
000000f0  00 00 00 00 00 e4 35 01  00 64 3a 01 00 10 27 00  |......5..d:...'.|
00000100  00 00 00 00 00 00 00 00  00 40 02 b0 01 73 74 72  |.........@...str|
00000110  66 6c 00 00 00 28 00 00  00 40 02 00 00 b0 01 00  |fl...(...@......|
00000120  00 01 00 10 00 58 56 49  44 00 c8 16 00 00 00 00  |.....XVID.......|
00000130  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

I tried using rar2fs with both
app-arch/unrar-5.3.11
app-arch/unrar-5.4.5

I suspect the output or format of libunrar has changed between the versions?

**Comment by hasse69** [comment]
Thanks for the report! Interesting, it seems to extract also the RAR header which of course is wrong!
But to be able to do anything I need the archive to be able to trouble shoot. Send info to my mail on how I can retrieve it.

**Comment by tfiskgul** [comment]
Thanks for the quick answer =) I sent you an email regarding the finer details of the rar file.

**Comment by tfiskgul** [comment]
After investigating some more with the help of @hasse69, we concluded that the cause was an upgrade from libunrar 5.3.11 to 5.4.5 without recompiling rar2fs. Recompiling rar2fs after switching between libunrar versions solves the issue. Thanks for the help @hasse69 :smiley:
