### ISSUE TITLE
Exclude directories without rar files

### ISSUE THREAD

**Issue by nubje** [hasse69/rar2fs#63]
Hey!

I am wondering if there is any way to "exclude" (make them not show up in rar2fs) directories that do not contain any rar files, or somehow set "include" and only allow certain file types.

**Comment by hasse69** [comment]
Not really. This is a RAR and pass-through file system. You might have a combination of files in RAR archives mixed with files that are not. It would not make much sense filtering out directories that does not have RAR files, if that is the case then some re-ordering of your files might be an option to make sure you mount a folder (with sub-folders) you know does not include ordinary files. But there might be scanning engines etc that relies on certain files being available so that could also cause problems.

**Comment by nubje** [comment]
Hey again, and thanks for the quick reply! :)

**Comment by hasse69** [comment]
Even if I personally do not see the point of this, if you can present a reasonable use-case to why a feature like this is needed it can at least stay as an open enhancement request.

**Comment by nubje** [comment]
It is a very specific use-case with Plex (and due to non-working .plexignore), but I'll try to lay it down;
Plex scans every directory it can find for media, so let's say you have numerous directories with sub-directories like "Cover" and/or "Trailer" it will scan those, which will not include any relevant media for Plex. And, if you use the "Update my library automatically" it will add file notifiers to those "unneeded" directories as well. 
So it's (hopefully) a way to speed up the indexing of the libraries.

**Comment by hasse69** [comment]
Ok, but have you actually measured the performance  with and without these extra directories? The overhead for scanning files in rar2fs is not the native files for sure. Are you certain it is really such a performance killer. I would rather suspect the scanning of the rars. And adding inotify watches on folder(s) that does not change might cost a few bytes of resources but not affect performance noticeably. Btw, have you tried to pull latest master that implements a cache of each folder? This will minimize the scanning or rars significantly and also speed up the PLEX indexer.

**Comment by nubje** [comment]
No, I haven't done any performance testing, this is just from the top of my head.
I'll take your word over mine any day when it comes to filesystems and performance.

I just recently (like today) found the "--seek-length" option, and that sure sped it up by _a lot_. 

```rar2fs v1.23.1 (DLL version 7)    Copyright (C) 2009 Hans Beckerus
FUSE library version: 2.9.4
fusermount version: 2.9.4
using FUSE kernel interface version 7.19```

**Comment by hasse69** [comment]
Yes, the --seek-length option might do wonders. But if you build a new version from master/HEAD I think you will be even more surprised of how much difference a cache will make to indexing speed.

**Comment by nubje** [comment]
```
rar2fs v1.23.1-git7f235f (DLL version 7)
```
Will try this version now - thanks for clearing things up! 👍

**Comment by hasse69** [comment]
Also, remember that for inotify to work in PLEX after remount of the rar2fs volume/mount point being watched you need to restart PMS.

**Comment by nubje** [comment]
Holy moly! That cache sure did wonders! :pray:

**Comment by hasse69** [comment]
Is this still a valid request? If not I would like to remove it from the list.

**Comment by nubje** [comment]
Feel free to remove it - there was other ways to speed it all up. Thanks!

**Comment by hasse69** [comment]
Thanks, will close it then.
