### ISSUE TITLE
commit 55e2de43557c68cb4810d4fb638f6bf15916903d has some regression

### ISSUE THREAD

**Issue by jyhpsycho** [hasse69/rar2fs#70]
Because of I can't reproduce this issue with crafted sample, I'll attach archive contents listing and some of debug messages with additional debug message on get_password():

```
$ unrar vta TEST.rar

UNRAR 5.40 freeware      Copyright (c) 1993-2016 Alexander Roshal

Archive: TEST.rar
Details: RAR 5

        Name: 未知艺术家 - 未知标题.wav
        Type: File
        Size: 291640988
 Packed size: 243314816
       Ratio: 83%
       mtime: 2015-09-21 20:29:29,476
  Attributes: ..A....
   CRC32 MAC: 9DEF73DD
     Host OS: Windows
 Compression: RAR 5.0(v50) -m5 -md=32M
       Flags: encrypted 

        Name: 未知艺术家 - 未知标题.cue
        Type: File
        Size: 877
 Packed size: 304
       Ratio: 34%
       mtime: 2015-09-21 20:24:49,262
  Attributes: ..A....
   CRC32 MAC: 30D6F0A7
     Host OS: Windows
 Compression: RAR 5.0(v50) -m5 -md=32M
       Flags: encrypted 

        Name: 未知艺术家 - 未知标题.log
        Type: File
        Size: 2928
 Packed size: 944
       Ratio: 32%
       mtime: 2015-09-21 20:30:42,559
  Attributes: ..A....
   CRC32 MAC: F4D3AF3B
     Host OS: Windows
 Compression: RAR 5.0(v50) -m5 -md=32M
       Flags: encrypted 

        Name: QO
        Type: Service
        Size: 136
 Packed size: 136
       Ratio: 100%
  Attributes: .B
     Host OS: Windows
 Compression: RAR 5.0(v50) -m0 -md=128K

     Service: EOF
```

```
unique: 4, opcode: OPEN (14), nodeid: 2, insize: 48, pid: 23228
open flags: 0x8000 /未知艺术家 - 未知标题.cue
rar2_open()   /未知艺术家 - 未知标题.cue
(23224) OPEN    /未知艺术家 - 未知标题.cue [0x0][called from 23228]
(23224) ALLOC   /未知艺术家 - 未知标题.cue [0x7f6a880601b0  ]
PIPE 0x7f6a88060250 created towards child 23229
get_password() : file = '/dev/shm/TEST/TEST.rar'
get_password() : l, the return value of get_vformat() = 1
get_password() : Trying password file ''
get_password() : Trying password file 'd'
get_password() : Can't open password file.
Reader thread started, fp=0x7f6a88060250
preload_index()   /未知艺术家 - 未知标题.cue
Reader thread wakeup, select()=1
   open[140095525355904] flags: 0x8000 /未知艺术家 - 未知标题.cue
   unique: 4, success, outsize: 32
unique: 5, opcode: READ (15), nodeid: 2, insize: 80, pid: 23228
read[140095525355904] 4096 bytes from 0 flags: 0x8000
rar2_read()   size=4096, offset=0, fh=140095525355904
PID 23224 calling lread_rar(), seq = 1, size=4096, offset=0/0
Reader thread wakeup, select()=1
Reader thread acknowledge
140095629821696 thread wakeup (1, 1)
   unique: 5, error: -1 (Operation not permitted), outsize: 16
unique: 6, opcode: READ (15), nodeid: 2, insize: 80, pid: 23228
read[140095525355904] 4096 bytes from 0 flags: 0x8000
rar2_read()   size=4096, offset=0, fh=140095525355904
PID 23224 calling lread_rar(), seq = 2, size=4096, offset=0/0
Reader thread wakeup, select()=1
Reader thread acknowledge
140095629821696 thread wakeup (1, 1)
   unique: 6, error: -1 (Operation not permitted), outsize: 16
unique: 7, opcode: FLUSH (25), nodeid: 2, insize: 64, pid: 23228
flush[140095525355904]
rar2_flush()   
(23224) FLUSH [0x7f6a880601b0  ][called from 23228]
lflush()   
   unique: 7, success, outsize: 16
unique: 8, opcode: RELEASE (18), nodeid: 2, insize: 64, pid: 0
release[140095525355904] flags: 0x8000
rar2_release()   
(23224) RELEASE [0x7f6a88060180    ]
Reader thread wakeup, select()=1
Reader thread stopped
child closed abnormalyPIPE 0x7f6a88060250 closed towards child 23229
(23224) FREE [0x7f6a88060180    ]
   unique: 8, success, outsize: 16
```

The strange is, when I created some sample with even same contents(extract it and recompress), same compression setting, same password, can't reproduce this issue. What the?! :-(

**Comment by jyhpsycho** [comment]
OK, I finally reproduced this issue with following instruction(Working directory : /dev/shm/TEST):
```
$ mkdir X
$ dd if=/dev/urandom of=X/TEST1 bs=16k count=1
$ dd if=/dev/urandom of=X/TEST2 bs=16k count=1
$ dd if=/dev/urandom of=X/TEST3 bs=16k count=1
$ cd X
$ rar a -m5 -ma5 -pTEST ../TEST.rar *
$ rm *
$ cd ..
$ echo "TEST" > TEST.pwd
$ /dev/shm/rar2fs/rar2fs --flat-only --show-comp-img TEST.rar X
$ hexdump X/TEST1
hexdump: X/TEST1: Operation not permitted
```

```
$ /dev/shm/rar2fs/rar2fs --version
rar2fs v1.23.1 (DLL version 7)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

I'll attach the sample : [TEST.zip](https://github.com/hasse69/rar2fs/files/768203/TEST.zip)

**Comment by hasse69** [comment]
Hmm, what version did you use exactly? That looks like released v1.23.1.
Tried your sample file on latest master and it works as expected. What did I miss? :(

**Comment by jyhpsycho** [comment]
Here's my git log:
```
$ git log --all --decorate --graph
* commit 98486d071ef8d5e42d04f9d3fbe4caa5c4a9f6c7 (HEAD, origin/master, origin/HEAD, master)
| Author: Hans Beckerus <hans.beckerus at gmail.com>
| Date:   Thu Feb 9 10:02:57 2017 +0100
| 
|     Fix wrong cache invalidation path
|     
|     Signed-off-by: Hans Beckerus <hans.beckerus at gmail.com>
| 
* commit eb8bfe9c48dd035d3af3025ffc53e718552c24a0
| Author: Hans Beckerus <hans.beckerus at gmail.com>
| Date:   Mon Feb 6 23:17:29 2017 +0100
| 
|     Fix a problem with absolute paths
|     
|     This patch will fix a problem with resolving archives created
|     with absolute paths reported in issue #68.
|     
|     Signed-off-by: Hans Beckerus <hans.beckerus at gmail.com>
```

I don't know why the git revision number is not attached on version string, though.

Yes, it behaves like there's no password file. See debug log.

**Comment by jyhpsycho** [comment]
Actually the tag v1.23.1 is commit aead8d54b5422e88057c7b5f4c01c7fc5fa3e804, which is the commit before 55e2de43557c68cb4810d4fb638f6bf15916903d, works as expected.

**Comment by hasse69** [comment]
Ok, I will check again but from what I read in you example you placed the password file in the wrong directory above X.

**Comment by hasse69** [comment]
This problem was fixed by commit 0911d421ec6e4939df537e09529796950427506b.
Will close this issue.

**Comment by jyhpsycho** [comment]
NO, It's not same issue to #65. I removed entire source tree and re-clone it, git tag version string is come back. I tried the last git version, and it still exists.
```
$ /dev/shm/rar2fs/rar2fs --version
rar2fs v1.23.1-git98486d0 (DLL version 7)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19
```

Are you can't reproduce this issue with provided sample?

**Comment by hasse69** [comment]
No, I did not say it was the same issue, only that the fixes made for issue #65 also seem to resolve this problem. Yes, I could reproduce it on all version up and until the one for issue #65, but not for any version after that.

**Comment by jyhpsycho** [comment]
For me, it still exist with commit 0911d421ec6e4939df537e09529796950427506b... OK, I need to dig into get_vformat(), and why it can't find base name for generating password file path. I'm not sure that it's really rar2fs' bug at this point, as you cannot reproduce it.

**Comment by jyhpsycho** [comment]
I'm working on current master now. Appending some debug message and I got:
```
get_password() : l[0] = -46
get_password() : l[1] = 18
get_password() : Looking for password file '/dev/shm/TEST/TEST.rar'
```
It seems like 'buffer underflow'... I need to check why get_vformat() returns negative value for base name length.

**Comment by jyhpsycho** [comment]
I got it! Actually get_vformat() returns 1 for l[0]. It's expected because it means scanning new-style volume name, but test sample is even not the part of volume set. But, due to [line 316](https://github.com/hasse69/rar2fs/blob/master/rar2fs.c#L316) on master, it becomes negative value.

Commenting out line 316, it works. Following is debug log on this case:
```
get_password() : l[0] = 1
get_password() : l[1] = 20
get_password() : l[0] = 1
get_password() : l[1] = 18
get_password() : Looking for password file '/.pwd'
get_password() : Looking for password file '/dev/shm/TEST/TEST.pwd'
```
But it's not work with new-style voume archive. I suggest [this patch](https://github.com/hasse69/rar2fs/files/772729/TEST.zip), which is working both testcase for me.

**Comment by jyhpsycho** [comment]
I guess it also work at line 316:
```
while (l[0] > 0 && file[l[0]] != '.') --l[0];
```

**Comment by hasse69** [comment]
Ok, before I can do anything I need to understand why this works fine for me but not for you.

**Comment by hasse69** [comment]
I still do not get why you see this but I don't on the same file. But despite that, the problem has always been that get_password() tries to guess the file format since after getting back from the callback the context is lost. I think it would be better to actually open the archive and check if it is a volume. I do not think I need the password for that.

**Comment by hasse69** [comment]
Try this patch, it will avoid trying to open the wrong file too...

[patch.txt](https://github.com/hasse69/rar2fs/files/773420/patch.txt)

**Comment by jyhpsycho** [comment]
Good, it seems to work with generated testcase both legacy and new volume name format, provided sample by me, and original archive I found this issue. Even it rejects mount without password file! Thanks :-)

I have one suggestion. It's good to reject mount operation without password file, but it may confuses user. If it provides error message including tried password file name, one easily understands why the mounting operation is rejected.

**Comment by hasse69** [comment]
Sometimes too much information is not helping either. I will consider some better pin-pointing of what went wrong but I am afraid that if I start doing it for this case I might need to uniquely describe every single case that might go wrong.

**Comment by hasse69** [comment]
Ok, you got it, see fef79e452259730f8ff120528747d214a82d772e.

**Comment by jyhpsycho** [comment]
Great! Thanks :-)
