### ISSUE TITLE
Writable "Layers" on top of rar2fs

### ISSUE THREAD

**Issue by gardar** [hasse69/rar2fs#73]
Disclaimer: I just had an idea that I'm not sure is directly related to rar2fs or even technically possible, but I hope it's ok that I'm throwing this idea/question out here since it's probably relevant to most rar2fs users.

Would it be possible to put a writable layer on top of rar2fs? Either with rar2fs or possibly another tool that would act as a transparent layer on top of rar2fs.
The transparent writeable layer would take all the data that's written to it and store it elsewhere and leave the rar files untouched.

The use case for such a feature would be to allow Emby/Plex/etc. to store metadata, subtitles, etc. in the same directory as the media files without touching the rar's.

I see two possible approaches.

- Directory/file based structure, where you would just replicate your rar2fs directory structure automatically under a writeable path, and then mount that somehow on top of rar2fs.
- Database/virtual filesystem that has your rar2fs mount indexed, and then stores writes/changes.

Inspired by the DrFTPD VFS I could see that the database/vfs index approach might be benefitial in other ways as well. It could contain file renaming like requested in #60  it could also store it own attributes such as size, modification time, ownership, checksum, etc. 
This could possibly solve the inotify issue and maybe has the potential of speeding up library scans? I could imagine accessing the vfs index could be a lot faster than browsing the directory structure.

What are your thoughts?

**Comment by magnub** [comment]
This already works today... my rar2fs mounts (volumes) are added to plex and plex stores its metadata (and writes) in the corresponding folder, or am I missing something here?

**Comment by gardar** [comment]
Ah good point, I should have been more clear.

I do not wish for the directories or files to be edited, not just the rars but also the dirs they are contained in.

**Comment by tfiskgul** [comment]
You could put an overlay on top of the rar2fs mount, such as [OverlayFS](https://en.wikipedia.org/wiki/OverlayFS) or [aufs](https://en.wikipedia.org/wiki/Aufs)?

**Comment by hasse69** [comment]
@gardar Thanks for the feature suggestion. However, I think I need to fully understand the purpose of the whole idea.

Do I understand correctly that what you want is basically a shadow layer/file-system for which writes are basically just locally stored cached information rather than actual data written to media? In that case I have a few follow-up questions like; what about rar2fs caching and adding contents? what happens to the data when the layer is removed? in what way would inotify behave differently over this layer than directly towards the rar2fs mount point? what is wrong with writing to the real mount point as can be done today? There are probably more questions, but let's start there.

**Comment by gardar** [comment]
@tfiskgul Thanks! That might actually be what I'm looking for! I'll have to take a better look at it, if someone here is using OverlayFS or aufs in such a way it would be interesting to see their setup.

@hasse69 

> Do I understand correctly that what you want is a shadow layer/file-system for which writes are basically just locally stored cached information rather than actual data written to media? 

Correct. What I'm trying to achive is to have the filesystem where the data can not be touched at all, in my case a read only nfs share that has rar2fs on top of it. But I could just as well have local data, curlftps, etc. that I would not want to be touched.

> In that case I have a few follow-up questions like; what about rar2fs caching and adding contents? what happens to the data when the layer is removed?

The idea I had was that I would mount a layer on top of rar2fs, or ideally have the layer integrated with rar2fs somehow. 

So in my case I would mount nfs > rar2fs > layer 
I would then point Emby/Plex/Whatever to the mounted layer.

Nothing actually happens to the data if the layer would be removed, it would just be unmounted. I could point my applications to the nfs or rar2fs mount point or mount the layer again or even a new layer if I want a fresh start. 

Have multiple layers could also be feasible, that way you could have one layer for emby and another for another service, and the data these services write would not conflict with each other.

> in what way would inotify behave differently over this layer than directly towards the rar2fs mount point? 

Well if we are talking about the "layer" approach then I don't see that it would behave differently. 
The reason I mentioned ionotify earlier was if you would go with the database approach.
The database approach would be that rar2fs would create a index database from the underlying filesystem, that database could then be modified and have data added to it, thus leaving the data untouched. The modifications could be renaming of files, adding content like pictures and text files etc.
When the database would be queried it could be a lot faster than cycling through the filesystem, which would make emby/plex/etc library updates a lot faster.

> what is wrong with writing to the real mount point as can be done today? 

For me personally I want my data to be un touched by media libraries, today I use one tool that writes its own metadata but in the future I might use something completely different which would not use the same metadata/metadata format and would write its own metadata and I really don't wish to clean all the old data up.
I try different software from time to time and I have unfortunately had to do this sort of a cleanup in the past, to avoid this I currently mount my media as read only.

I could imagine other scenarios as well, where users have their media mounted as read only from a ftp server with curlftpfs, or torrents with btfs, etc.

**Comment by hasse69** [comment]
A layer approach would require nothing from rar2fs and a file system on top of rar2fs should be able to provide such functionality. The database approach is a completely different implementation of what is there today and if you ask me it sounds a bit specific to your use-case? Even if the database is stored on media and after unmount what should be considered the master? The real source or the data base? Changes to the underlying file system needs to be handled as well and it does not seem like a trivial task to keep them in sync. The idea is not bad, but I do think it will make it into the design of rar2fs. Not in a foreseeable future at least.
