### ISSUE TITLE
mkvs in rar archives with partXX names unplayable

### ISSUE THREAD

**Issue by magnub** [hasse69/rar2fs#77]
Hi 

I'm unable to play mkvs inside archives with partXX.rar naming schemes with rar2fs 1.25.1
I can see the mkv file inside the archives but e.g. mpv and plex fails with playback with:
Failed to recognize file format.

archives with rXX naming have no issues

**Comment by hasse69** [comment]
I need some more details about the archive since I cannot reproduce it myself.
Compressed or store mode? RAR4 or RAR5 format? Size of .mkv?

**Comment by hasse69** [comment]
I have tested both a 1GiB and a 8GiB file split using 150MiB volume parts using new style archive (,partXX) and then performed a binary diff with the original file. I still do not see any problems so I really need some more input on this one.

**Comment by hasse69** [comment]
Are you using --seek-length=1 by any chance? I think I can see an issue there...
As a workaround try to use --seek-length=2 instead. I will look deeper into why --seek-length=1 suddenly stopped working for new naming scheme.

**Comment by magnub** [comment]
Sorry for not being able to answer earlier, yes I'm using - - seek-length=1 I'll switch to 2 for now then thanks.

**Comment by hasse69** [comment]
There is now a patch release fixing the incorrect volume count logic , https://github.com/hasse69/rar2fs/releases/tag/v1.25.2.
Closing this.

**Comment by magnub** [comment]
Thanks for this, works fine now!
