### ISSUE TITLE
Incorrect high-precision timestamp handling

### ISSUE THREAD

**Issue by jyhpsycho** [hasse69/rar2fs#79]
* HOW TO REPRODUCE
```
touch X
rar a -ma5 TEST.rar X
rm X
mkdir Y
rar2fs -o ro,allow_other --show-comp-img TEST.rar Y
ls -lA --full-time Y
```
* NOTE : Without removing X in current directory before mount, it shows invalid timestamp. Since that is another bug, I'll file it later.

* EXPECTED OUTPUT
```
total 0
-rw-r--r-- 1 rar_work users 0 2017-07-22 12:39:03.923564800 +0900 X
```

* ACTUAL RESULT
```
total 4
-rw-r--r-- 1 rar_work users 0 6356-07-07 14:06:32.356480000 +0900 X
```

* SYSTEM INFORMATION
```
$ rar2fs --version
rar2fs v1.25.2 (DLL version 8)    Copyright (C) 2009 Hans Beckerus
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it under
certain conditions; see <http://www.gnu.org/licenses/> for details.
FUSE library version: 2.9.7
fusermount version: 2.9.7
using FUSE kernel interface version 7.19

$ emerge --search '%^unrar$'

[ Results for search key : %^unrar$ ]
Searching...

*  app-arch/unrar
      Latest version available: 5.5.5-r1
      Latest version installed: 5.5.5-r1
      Size of files: 216 KiB
      Homepage:      http://www.rarlab.com/rar_add.htm
      Description:   Uncompress rar files
      License:       unRAR

[ Applications found : 1 ]
```

* ADDITIONAL NOTES
  - From libunrar 5.5, High-precision timestamp API is changed, from GetRaw() to GetUnixNS(). GetRaw() provides Windows' FILETIME value that 100 ns unit timestamp from 1601-01-01. But, GetUnixNS() provides Unix's high-precision timestamp, which has 1 ns unit and from 1970-01-01.
  - That means, current rar2fs behavior with libunrar 5.5+ is invalid, treating 1 ns unit timestamp as 100 ns one.
  - I'll attach patch for handling that correctly. I tested this patch with libunrar 5.4.5, 5.5.3(build from source), and 5.5.5(Installed on my system). Tell me if it has any regression.

[timestamp-fix.patch.zip](https://github.com/hasse69/rar2fs/files/1167100/timestamp-fix.patch.zip)

**Comment by hasse69** [comment]
Thanks. I will take a look at the patch.

**Comment by hasse69** [comment]
Patch merged. Closing this.
