### ISSUE TITLE
Clean compile of rar2fs and dokan in Cygwin 64 bit/Windows 10 64 bit causes segmentation fault

### ISSUE THREAD

**Issue by janosek** [hasse69/rar2fs#82]
Hello,

This is more of a question than a defect, as you were able to get rar2fs to work with Dokan.   I am trying it out now but after cleanly compiling, I get a segmentation fault even when running rar2fs -h
Here are my steps:

1. Download DOKAN installer here: https://github.com/dokan-dev/dokany/releases/download/v1.0.3/Dokan_x64.msi
2. Install DOKAN
3.  Cd /
4. git clone https://github.com/hasse69/rar2fs.git
5. cd rar2fs
6. wget http://www.rarlab.com/rar/unrarsrc-5.5.8.tar.gz
7.  tar -zxvf unrarsrc-5.5.8.tar.gz
8. sed s/-fPIC//g -i unrar/makefile
9. make -C unrar lib
10. git clone https://github.com/dokan-dev/dokany.git
11. cp /cygdrive/c/Program Files/Dokan/DokanLibrary-1.0.2/* /rar2fs/dokany/dokan_fuse/include
12. autoreconf -fi
13. ./configure --with-fuse=/rar2fs/dokany/dokan_fuse/include/ --with-fuse-lib=/rar2fs/dokany/dokan_fuse/include/
14. make
15. make install

I run:
rar2fs -h

Exception: STATUS_ACCESS_VIOLATION at rip=7FFE7DF66A60
rax=0000000000000012 rbx=000000018030F7C0 rcx=0000000000000056
rdx=000000018030F7C0 rsi=0000000000000000 rdi=00000000FFFFC920
r8 =000000000000002D r9 =0000000100404C00 r10=000000010043A470
r11=00000000FFFFC910 r12=00000000FFFFCA80 r13=0000000100404C00
r14=0000000529653040 r15=0000000000000000
rbp=00000000FFFFC971 rsp=00000000FFFFC868
program=C:\cygwin\usr\local\bin\rar2fs.exe, pid 10960, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
000FFFFC971  7FFE7DF66A60 (00100404C00, 00000000000, 006000128AA, 00000000000)
000FFFFC971  7FFE7DF671D6 (00000000000, 00000000000, 00100404C00, 0018030F7C0)
000FFFFC971  7FFE7DF67625 (00100000000, 00000000000, 000FFFFCDF0, 00100000000)
000FFFFCA50  005296514DE (00000000000, 0010043A460, 00100404C00, 001801C26A0)
000FFFFCAA0  00100438BF2 (00000000020, 30001000000FF00, 001800477A1, 001800468D0)
000FFFFCCC0  00180047812 (00000000000, 00000000000, 00000000000, 00000000000)
00000000000  001800455E3 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180045694 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

How do I run this afterwards? Will the same command below still work?
rar2fs --seek-length=1 -d -f /cygdrive/d/files/seed -o uid=-1,gid=-1 -o 'VolumePrefix=\\Janosek-pc\\x' X:

**Comment by hasse69** [comment]
> How do I run this afterwards? Will the same command below still work?

No. it will not work because the arguments supported by dokan is different to WinFSP.

Please attach your config.log.
Also send the result of `ldd ./rar2fs.exe'

My initial guess would be that there are some left-overs in your Cygwin enviornment from a previous install of WinFSP.

**Comment by hasse69** [comment]
From the dokan wiki, this can be read:

"The cygdokanfuse1.dll distributed is compiled by cygwin gcc. You can also build it yourself with:

```
cd dokan_fuse/
cmake .
make
```

Be aware that cygdokanfuse1.dll has dependencies to cygwin1.dll, cyggcc_s-seh-1.dll and cygstdc++-6.dll."

Did you build this yourself or did you install the one that was distributed with the package?

**Comment by janosek** [comment]
Something different, but still not working.
I completely deleted my cygwin folder and reinstalled.  I then followed the steps below (I kept the sed step because its easier than editing the unrar make file manually and uncommenting out the cygwin section which is the same as the linux section after the sed command).  There are no compile time errors. the ./configure works fine.. but...

When I run rar2fs.exe  -h I literally get nothing:
****************************************************
Software Install@Janosek-PC /rar2fs
$ rar2fs.exe -h

Software Install@Janosek-PC /rar2fs
$
****************************************************
Here are the steps I ran this time:
1. Download DOKAN installer here: https://github.com/dokan-dev/dokany/releases/download/v1.0.3/DokanSetup.exe
2. Install DOKAN
In Cygwin terminal:
3. Cd /
4. git clone https://github.com/hasse69/rar2fs.git
5. cd rar2fs
6. wget http://www.rarlab.com/rar/unrarsrc-5.5.8.tar.gz
7. tar -zxvf unrarsrc-5.5.8.tar.gz
8. sed s/-fPIC//g -i unrar/makefile
9. make -C unrar lib
10. wget https://github.com/dokan-dev/dokany/releases/download/v1.0.3/dokan.zip
11. unzip dokan.zip
12. cp /rar2fs/x64/Cygwin/cygdokanfuse1.dll /usr/bin
13. cp -R /rar2fs/x64/Cygwin/lib/* /usr/lib
14. cp -R /rar2fs/x64/Cygwin/include/* /usr/include
15. mv /usr/lib/libdokanfuse1.dll.a  /usr/lib/libcygdokanfuse1.a
16. autoreconf -fi
17. ./configure
18. make
19. make install

**Comment by janosek** [comment]
Figured out the problem.  Its a permissions issue.  

I when into /usr/bin, /usr/lib and usr/include and chmod 777 all the files I copied and it worked after that.  I will update my steps accordingly (so I don't have to rethink how to do this)

**Comment by janosek** [comment]
Serviio is indexing.  So far so good.  Let me know if you have any more kernel patches you want me to try.

**Comment by hasse69** [comment]
Please report back in issue #81 since it is easier to track.

**Comment by eskimos20** [comment]
I´ve tried this install and got it to work, however I think Dokan is a bit unstable and the mounted rar2fs share was unmounted from time to time, usually after a couple of hours or a day at tops. 

I am also running rar2fs on a Linux Mint virtual machine and in that enviroment it works great. 

Is there a simple 1,2,3,4... guide like the one above for WINFSP, Cygwin and rar2fs ? 

/Eskimos20

**Comment by hasse69** [comment]
If you follow this thread (be aware it is a lot) https://github.com/hasse69/rar2fs/issues/75 I think you have what you need. The process of installing Cygwin and rar2fs is the same, it is the back-end that is different only. I will lock this thread now and if you have further questions or issues please file a new issue report.
