### ISSUE TITLE
Build s3fs with WinFSP layer?

### ISSUE THREAD

**Issue by chrilith** [hasse69/rar2fs#88]
Hi,

I [forked](https://github.com/chrilith/s3fs-fuse) `s3fs-fuse` and created a [pull-request](https://github.com/s3fs-fuse/s3fs-fuse/pull/712) to make s3fs compile under Cygwin.

My problem now is that it doesn't work. :)

First I had a "mount point in use" error. So, reading details from #75 I found that `stat()` calls may be modified. For testing purpose, I removed the whole check in `my_fuse_opt_proc()` (s3fs.cpp). After that, and changing `check_passwd_file_perms()` too to prevent "credentials file %s should not have others permissions.". The drive is now created with:
```
$  s3fs myBucket k: -o passwd_file=~/passwd.s3fs
```

But still, with "access denied" problem. So, I tried to append `-ouid=65792,gid=65792,umask=0`.

With a new error: "K: is unreachable. Invalid path name"
(this is translated, don't know the correct english version of this error).

Any clue?
Thanks!

**Comment by hasse69** [comment]
Hello, I think you should contact the author of WinFSP with questions like this (https://github.com/billziss-gh). I would probably only send you in the wrong direction if I tried to answer your questions :)

**Comment by chrilith** [comment]
Oh man, sorry... I've bounced on so many threads I posted on the wrong project! :)

Sorry again!
