### ISSUE TITLE
Installation on Raspbian

### ISSUE THREAD

**Issue by Moe1986** [hasse69/rar2fs#89]
Hello, can anybody tell me how I can install this application?
I have downloaded "rar2fs-1.26.0.tar.gz"  and followed the installation tutorial:

`./configure && make && make install`
But it ends up with an error like fuse.h couldn't be found:

`Cannot find fuse.h - add alternative include search path using
--with-fuse and rerun configure.`

Sorry but I'm not a Linux guru.

**Comment by Moe1986** [comment]
solved it

**Comment by hasse69** [comment]
Yea, nice to hear you solved it. Sorry I was not able to reply but I am traveling and have very limited access to mail and github. Please close the issue if you think nothing more needs to be done.
