### ISSUE TITLE
Libunrar 5.6.1

### ISSUE THREAD

**Issue by malmers** [hasse69/rar2fs#90]
When using libunrar 5.6.1, unrared files looks empty.

Downgrading back to libunrar version 5.5.8 solves the problem.

**Comment by hasse69** [comment]
Thanks for the issue report. Will look into it.
Unfortunately backwards compatibility is not always guaranteed by libunrar and stepping from 5.5.x to 5.6.x could very likely break.

**Comment by hasse69** [comment]
I now tried using libunrar 5.6.1 and I don't seem to experience the same problem as you do?
Can you please describe a bit more in detail what observations you made?
Also, double check that if you are not linking statically with `libunrar.a` that you actually replaced the library `libunrar.so` in your system library search path.

**Comment by malmers** [comment]
I installed rar2fs via [aur](https://aur.archlinux.org/packages/rar2fs). It seems like the PKGBUILD is outdated and uses libunrar 5.5.7 to build the program. I guess I should have checked that before creating this issue.

Thanks for the quick response.

**Comment by hasse69** [comment]
No worries. Actually good that you reported it, pushed me into actually testing the new release of libunrar :) And by doing so I also discovered a new problem not related to this issue.
