### ISSUE TITLE
Pass rar2fs options via fstab

### ISSUE THREAD

**Issue by konstantinblaesi** [hasse69/rar2fs#94]
How do you pass options such as `--seek-length=1` via fstab? Does it make sense to set this to 1 to improve performance? In my short testing I didn't encounter any issues.

**Comment by hasse69** [comment]
I think you can check out this issue https://github.com/hasse69/rar2fs/issues/8, most likely only the last post from me is of interest to you.
If you need to use `--seek-length` or not is basically based on your own user experience. If you mount a folder with a huge amount of RAR volumes, it would enhance the performance significantly when doing a folder lookup. But once that is done information is cached so the increased performance need is basically only there at the first access to an archive or after the cache has been invalidated. Then it does not really matter any more. There is a drawback with using a very low seek length though, and that is if the volume has many files that spans across many volume parts, they might not show up at all.

**Comment by hasse69** [comment]
Closing this since I do not think there is much more to add.
