### ISSUE TITLE
Installed on Synology

### ISSUE THREAD

**Issue by lordvalium** [hasse69/rar2fs#99]
Are there tips how to install rar2fs on Synology?

**Comment by hasse69** [comment]
The Synology NAS is as any other Linux target. You need to install a proper toolchain and build it yourself unless the distribution it uses provides a pre-compiled and install-able package. I suggest you check on some Synology NAS forums for further information.

**Comment by hasse69** [comment]
Closing this since it is not an issue with rar2fs.

**Comment by hasse69** [comment]
Check this one out
https://sourceforge.net/projects/dsgpl/files/DSM%206.1%20Tool%20Chains/Intel%20x86%20Linux%204.4.15%20(Apollolake)/

**Comment by hasse69** [comment]
It is a cross-compilation toolchain, check with some Synology NAS forum if you do not know how it is used.
